CREATE DATABASE idatabase;
use idatabase;
 CREATE TABLE usuario (
  idusuario INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(100) NULL,
  pass INTEGER UNSIGNED NULL,
  tipo VARCHAR(20) NULL,
  PRIMARY KEY(idusuario)
);

CREATE TABLE persona (
  ci INTEGER UNSIGNED NOT NULL,
  idusuario INTEGER UNSIGNED NOT NULL,
  nombres VARCHAR(100) NULL,
  paterno VARCHAR(100) NULL,
  materno VARCHAR(100) NULL,
  telefono INTEGER UNSIGNED NULL,
  direccion TEXT NULL,
  PRIMARY KEY(ci),
  FOREIGN KEY(idusuario)
    REFERENCES usuario(idusuario)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);

CREATE TABLE Personal (
  idPersonal INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ci INTEGER UNSIGNED NOT NULL,
  Rol VARCHAR(100) NULL,
  PRIMARY KEY(idPersonal),
  FOREIGN KEY(ci)
    REFERENCES persona(ci)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);

CREATE TABLE cliente (
  idcliente INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ci INTEGER UNSIGNED NOT NULL,
  razon_social VARCHAR(100) NULL,
  PRIMARY KEY(idcliente),
  FOREIGN KEY(ci)
    REFERENCES persona(ci)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);
